const path = require('path');
const dist = path.resolve(__dirname, 'dist');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const HtmlWebpackHarddiskPlugin = require('html-webpack-harddisk-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');

module.exports = {
  entry: './src/index.ts',
  mode: 'development',
  watch: true,
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        loader: 'ts-loader',
        exclude: /node_modules/,
        options: {
          configFile: 'tsconfig.json',
        },
      },
      {
        test: /mxClient\.js$/,
        loader: `exports-loader?${[
          'mxAbstractCanvas2D',
          'mxActor',
          'mxAnimation',
          'mxArrow',
          'mxArrowConnector',
          'mxAutoSaveManager',
          'mxCell',
          'mxCellAttributeChange',
          'mxCellEditor',
          'mxCellHighlight',
          'mxCellMarker',
          'mxCellOverlay',
          'mxCellRenderer',
          'mxCellState',
          'mxCellStatePreview',
          'mxCellTracker',
          'mxChildChange',
          'mxCircleLayout',
          'mxClient',
          'mxClipboard',
          'mxCloud',
          'mxCodec',
          'mxCodecRegistry',
          'mxCollapseChange',
          'mxCompactTreeLayout',
          'mxCompositeLayout',
          'mxConnectionConstraint',
          'mxConnectionHandler',
          'mxConnector',
          'mxConstraintHandler',
          'mxConstants',
          'mxCoordinateAssignment',
          'mxCurrentRootChange',
          'mxCylinder',
          'mxDefaultKeyHandler',
          'mxDefaultPopupMenu',
          'mxDefaultToolbar',
          'mxDictionary',
          'mxDivResizer',
          'mxDoubleEllipse',
          'mxDragSource',
          'mxEdgeHandler',
          'mxEdgeLabelLayout',
          'mxEdgeSegmentHandler',
          'mxEdgeStyle',
          'mxEditor',
          'mxElbowEdgeHandler',
          'mxEllipse',
          'mxEvent',
          'mxEventObject',
          'mxEventSource',
          'mxFastOrganicLayout',
          'mxForm',
          'mxGeometry',
          'mxGeometryChange',
          'mxGraph',
          'mxGraphAbstractHierarchyCell',
          'mxGraphHandler',
          'mxGraphHierarchyEdge',
          'mxGraphHierarchyModel',
          'mxGraphHierarchyNode',
          'mxGraphLayout',
          'mxGraphModel',
          'mxGraphSelectionModel',
          'mxGraphView',
          'mxGuide',
          'mxHandle',
          'mxHexagon',
          'mxHierarchicalLayout',
          'mxHierarchicalLayoutStage',
          'mxImage',
          'mxImageBundle',
          'mxImageExport',
          'mxImageShape',
          'mxKeyHandler',
          'mxLabel',
          'mxLayoutManager',
          'mxLine',
          'mxLog',
          'mxMedianHybridCrossingReduction',
          'mxMinimumCycleRemover',
          'mxMorphing',
          'mxMouseEvent',
          'mxMultiplicity',
          'mxObjectCodec',
          'mxOutline',
          'mxPanningHandler',
          'mxPanningManager',
          'mxParallelEdgeLayout',
          'mxPartitionLayout',
          'mxPoint',
          'mxPolyline',
          'mxPopupMenu',
          'mxPopupMenuHandler',
          'mxPrintPreview',
          'mxRadialTreeLayout',
          'mxRectangle',
          'mxRectangleShape',
          'mxRhombus',
          'mxRootChange',
          'mxRubberband',
          'mxSelectionCellsHandler',
          'mxSelectionChange',
          'mxShape',
          'mxStackLayout',
          'mxStencil',
          'mxStyleChange',
          'mxStyleRegistry',
          'mxStylesheet',
          'mxSvgCanvas2D',
          'mxSwimlane',
          'mxSwimlaneLayout',
          'mxSwimlaneManager',
          'mxSwimlaneModel',
          'mxSwimlaneOrdering',
          'mxTemporaryCellStates',
          'mxTerminalChange',
          'mxText',
          'mxToolbar',
          'mxTooltipHandler',
          'mxTriangle',
          'mxUndoableEdit',
          'mxUndoManager',
          'mxUtils',
          'mxValueChange',
          'mxVertexHandler',
          'mxVisibleChange',
          'mxWindow',
          'mxXmlCanvas2D',
          'mxXmlRequest',
        ].join(',')}`,
      },
    ],
  },
  resolve: {
    extensions: ['.tsx', '.ts', '.js'],
  },
  output: {
    filename: 'bundle.js',
    path: dist,
  },
  devServer: {
    contentBase: dist,
    compress: true,
    port: 5005,
  },
  plugins: [
    new HtmlWebpackPlugin({
      title: 'Demo visu BPMN',
      filename: 'index.html',
      template: 'src/index.html',
      alwaysWriteToDisk: true,
      minify: false,
    }),
    new HtmlWebpackHarddiskPlugin({
      outputPath: path.resolve(__dirname, 'dist'),
    }),
    new CopyWebpackPlugin([
      {
        from: 'src/static',
        to: dist,
      },
      {
        context: 'src',
        from: '*.d.ts',
      },
    ]),
  ],
};
